services:
  traefik:
    image: traefik:latest
    container_name: traefik
    hostname: traefik-server
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 443:443
      - 5432:5432
    volumes:
      - traefik.http.routers.traefik-secure.service=api@internal
    networks:
      - default
networks:
  default:
    name: traefik-network
