
global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: INFO  #WARN
  format: json
  #filePath: /var/log/traefik/server.log
accesslog:
  format: json
  filePath: /var/log/traefik/access.log

middlewares:
  admin-auth:
    basicAuth:
      users:
        - "admin:at747372$#@"
api:
  insecure: false
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: amirtaherkhani@outlook.com
      storage: /etc/traefik/certs/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false